exp_name: emb_nnet_train15_current
model: emb
hidden_nodes: 50
epochs: 30
lr: 0.01
verbose: 1
batch_size: 1024
emb_size: 2
add_current_error: True
current_error_len: 30
pickled_sets: 15_16_current30.pkl