exp_name: emb_nnet_train15_current_aux
model: emb
epochs: 40
lr: 0.001
verbose: 1
hidden_nodes: 30
batch_size: 1024
emb_size: 2
add_current_error: True
current_error_len: 30
use_aux: True
pickled_sets: aux_15_16_current30.pkl